stages:
  - build
  - manifest

.build:
  stage: build
  tags:
    - shell-executor
    - amd64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./build-image.sh $IMAGE_TAG $UBUNTU_VERSION
    # Push to local registry...
    - docker push $IMAGE_TAG
    # Push to Docker Hub...
    - export DOCKER_HUB_IMAGETAG="${IMAGE_TAG/$CI_REGISTRY\//}"
    - docker tag $IMAGE_TAG $DOCKER_HUB_IMAGETAG
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_IMAGETAG

build-18.04-amd64:
  extends: .build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:18.04-amd64
    UBUNTU_VERSION: "18.04"
    
build-16.04-amd64:
  extends: .build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:16.04-amd64
    UBUNTU_VERSION: "16.04"
    
build-18.04-armhf:
  extends: .build
  tags:
    - shell-executor
    - armhf
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:18.04-armhf
    UBUNTU_VERSION: "18.04"
    
build-16.04-armhf:
  extends: .build
  tags:
    - shell-executor
    - armhf
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:16.04-armhf
    UBUNTU_VERSION: "16.04"

.manifest:
  stage: manifest
  tags:
    - shell-executor
    - armhf
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    IMAGE_TAG: $CI_REGISTRY_IMAGE:16.04
  script:
    # Push manifest to local registry...
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker manifest create -a $IMAGE_TAG ${IMAGE_TAG}-amd64 ${IMAGE_TAG}-armhf || true
    - docker manifest annotate $IMAGE_TAG ${IMAGE_TAG}-armhf --arch armv7l || true
    - docker manifest push $IMAGE_TAG || true
    # Push manifest to Docker Hub...
    - export DOCKER_HUB_IMAGETAG="${IMAGE_TAG/$CI_REGISTRY\//}"
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker manifest create -a $DOCKER_HUB_IMAGETAG ${DOCKER_HUB_IMAGETAG}-amd64 ${DOCKER_HUB_IMAGETAG}-armhf || true
    - docker manifest annotate $DOCKER_HUB_IMAGETAG ${DOCKER_HUB_IMAGETAG}-armhf --arch armv7l || true
    - docker manifest push $DOCKER_HUB_IMAGETAG || true

manifest-16.04:
  extends: .manifest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:16.04

manifest-18.04:
  extends: .manifest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:18.04
