image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-18.04:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/18.04:$CI_COMMIT_REF_SLUG
  
  script:
    - docker build -t $IMAGE_TAG docker-18.04
    - docker push $IMAGE_TAG
    
build-16.04:
  stage: build

  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/16.04:$CI_COMMIT_REF_SLUG

  script:
    - docker build -t $IMAGE_TAG docker-16.04
    - docker push $IMAGE_TAG
